[package]
edition = "2024"
name = "perftest"
version = "0.0.1"
authors = ["Julius Armbruester <julius.armbruester@hhu.de>"]

[lib]
crate-type = ["staticlib"]
path = "src/perftest.rs"
test = false
doctest = false
bench = false

[dependencies]
# Local dependencies
terminal = { path = "../../library/terminal" }
rdma = { path = "../../library/rdma" }
runtime = { path = "../../library/runtime" }
network = { path = "../../library/network" }

core3 = { version = "0.1", default-features = false }
#smoltcp = { version = "0.12", default-features = false, features = ["proto-ipv4"] }
